In [1]:
import pandas as pd

from sklearn.datasets import load_iris

data = load_iris()

df = pd.DataFrame(data.data, columns=data.feature_names)

df['target'] = data.target

In [3]:
df.to_csv('data')

In [8]:

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df[data.feature_names], df['target'], random_state=0)

In [9]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth = 2, 

                             random_state = 0)
clf.fit(X_train, Y_train)
clf.predict(X_test.iloc[0].values.reshape(1, -1))

# Predict for multiple observations

clf.predict(X_test[0:10])

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
import numpy as np

pipeline = Pipeline([
    ('impute', SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=0.)),
    ('scale', StandardScaler()),
    ('model', DecisionTreeClassifier(max_depth = 2, random_state = 0))
])
pipeline.fit(X_train, Y_train)
pipeline.predict(X_test[0:10])             

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

In [17]:
import joblib
# Save
joblib.dump(pipeline, 'clf.pkl')
# restore
clf3 = joblib.load('clf.pkl')
print(clf3.predict(X_test[0]))#预测第一个X


[2 1 0 2 0 2 0 1 1 1]


In [18]:
import os
os.dir()

AttributeError: module 'os' has no attribute 'dir'

In [19]:
import sys
print(sys.path)

['/Users/qinyuan/MFE2022Python/Homeworks/HW1/Yuan_QIN/UCB-MFE-python-preprogram/Homeworks/HW9/Yuan_Qin/Data', '/Users/qinyuan/opt/anaconda3/lib/python38.zip', '/Users/qinyuan/opt/anaconda3/lib/python3.8', '/Users/qinyuan/opt/anaconda3/lib/python3.8/lib-dynload', '', '/Users/qinyuan/opt/anaconda3/lib/python3.8/site-packages', '/Users/qinyuan/opt/anaconda3/lib/python3.8/site-packages/aeosa', '/Users/qinyuan/opt/anaconda3/lib/python3.8/site-packages/locket-0.2.1-py3.8.egg', '/Users/qinyuan/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions', '/Users/qinyuan/.ipython']


In [23]:
X_test.iloc[0]

sepal length (cm)    5.8
sepal width (cm)     2.8
petal length (cm)    5.1
petal width (cm)     2.4
Name: 114, dtype: float64

In [24]:
X_test[0]

KeyError: 0

In [42]:
pipeline.predict(np.array(X_test.iloc[37
                                      :38]))[0]

2

In [35]:
len(X_test)

38